In [22]:
import numpy as np

# WRONG VERSION of creating vectors --------------
# init array, rank 1 array, inconsistent format ... don't use it
a = np.random.randn(5)

# !!!BUT, if you have one, you can respahe it => "a = a.reshape((5,1))" !!!

In [3]:
print(a)

[ 0.0567136   0.68117066 -0.72485769 -0.11468964  0.62878081]


In [4]:
# that the issue with shape ... "(5,)"
print(a.shape)

(5,)


In [5]:
# a.T === a !!!! it's wrong, we don't have to use it like that!
print(a.T)

[ 0.0567136   0.68117066 -0.72485769 -0.11468964  0.62878081]


In [7]:
# Wrong! it should be matrix 5x5, but got just number!
print(np.dot(a, a.T))

1.401147592886426


In [8]:
# CORRECT VERSION of creating vectors ------------

In [5]:
# correct format/shape of matrix
a = np.random.randn(5, 1) 
# or use it like (1,5)
print(a)

[[-1.21513113]
 [-2.86781635]
 [-0.22766451]
 [ 0.90552815]
 [-0.37284002]]


In [8]:
# correct transposed (транспонированная) matrix
print(a.T)

[[-1.21513113 -2.86781635 -0.22766451  0.90552815 -0.37284002]]


In [13]:
# Correct multiply of a and a.T matrix (5,1) * (1,5) => (5,5) matrix
print(np.dot(a, a.T))

[[ 1.47654367  3.48477293  0.27664223 -1.10033545  0.45304952]
 [ 3.48477293  8.22437063  0.6529     -2.59688844  1.06923672]
 [ 0.27664223  0.6529      0.05183113 -0.20615662  0.08488244]
 [-1.10033545 -2.59688844 -0.20615662  0.81998123 -0.33761714]
 [ 0.45304952  1.06923672  0.08488244 -0.33761714  0.13900968]]


In [21]:
# To be sure about the shape we can use "assert"
assert(a.shape == (5, 1))
# And it's like documentation, good practice to use it in the code
print('Correct format')

Correct format
